// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkS2PK5YGoTqVsOphaqQOxYVfJDC1AC6s',
    appId: '1:298918535780:web:4f4d0b5a9477ad80f47571',
    messagingSenderId: '298918535780',
    projectId: 'healthpal-ej',
    authDomain: 'healthpal-ej.firebaseapp.com',
    storageBucket: 'healthpal-ej.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkzci5nxiutCbDp1Zut4XAhN8C9vWdL3w',
    appId: '1:298918535780:android:a13144363eb9744cf47571',
    messagingSenderId: '298918535780',
    projectId: 'healthpal-ej',
    storageBucket: 'healthpal-ej.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkHZegT3nbfIFYd8_p9eLTfmuIHO4Tl4M',
    appId: '1:298918535780:ios:23a70a133d67c838f47571',
    messagingSenderId: '298918535780',
    projectId: 'healthpal-ej',
    storageBucket: 'healthpal-ej.firebasestorage.app',
    iosBundleId: 'com.example.healthPal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkHZegT3nbfIFYd8_p9eLTfmuIHO4Tl4M',
    appId: '1:298918535780:ios:23a70a133d67c838f47571',
    messagingSenderId: '298918535780',
    projectId: 'healthpal-ej',
    storageBucket: 'healthpal-ej.firebasestorage.app',
    iosBundleId: 'com.example.healthPal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkS2PK5YGoTqVsOphaqQOxYVfJDC1AC6s',
    appId: '1:298918535780:web:edbe73a54d229f8df47571',
    messagingSenderId: '298918535780',
    projectId: 'healthpal-ej',
    authDomain: 'healthpal-ej.firebaseapp.com',
    storageBucket: 'healthpal-ej.firebasestorage.app',
  );
}
