// Mocks generated by Mockito 5.4.6 from annotations
// in health_pal/test/helpers/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:io' as _i10;

import 'package:health_pal/core/network/result.dart' as _i7;
import 'package:health_pal/features/auth/data/datasource/auth_local_datasource.dart'
    as _i12;
import 'package:health_pal/features/auth/data/datasource/auth_remote_datasource.dart'
    as _i11;
import 'package:health_pal/features/auth/data/model/user_model.dart' as _i3;
import 'package:health_pal/features/auth/domain/entity/user_entity.dart' as _i8;
import 'package:health_pal/features/auth/domain/repository/auth_repository.dart'
    as _i5;
import 'package:health_pal/features/home/data/datasource/home_local_datasource.dart'
    as _i22;
import 'package:health_pal/features/home/data/datasource/home_remote_datasource.dart'
    as _i18;
import 'package:health_pal/features/home/data/model/banner_model.dart' as _i19;
import 'package:health_pal/features/home/data/model/specialization_model.dart'
    as _i21;
import 'package:health_pal/features/home/data/model/upcoming_appointment_model.dart'
    as _i20;
import 'package:health_pal/features/home/data/model/user_profile_model.dart'
    as _i4;
import 'package:health_pal/features/home/domain/entity/banner_entity.dart'
    as _i14;
import 'package:health_pal/features/home/domain/entity/specialization_entity.dart'
    as _i16;
import 'package:health_pal/features/home/domain/entity/upcoming_appointment_entity.dart'
    as _i15;
import 'package:health_pal/features/home/domain/entity/user_profile_entity.dart'
    as _i17;
import 'package:health_pal/features/home/domain/repository/home_repository.dart'
    as _i13;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:supabase_flutter/supabase_flutter.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthResponse_0 extends _i1.SmartFake implements _i2.AuthResponse {
  _FakeAuthResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserModel_1 extends _i1.SmartFake implements _i3.UserModel {
  _FakeUserModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserProfileModel_2 extends _i1.SmartFake
    implements _i4.UserProfileModel {
  _FakeUserProfileModel_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i5.AuthRepository {
  @override
  bool get isLoggedIn =>
      (super.noSuchMethod(
            Invocation.getter(#isLoggedIn),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i6.Future<_i7.Result<_i8.UserEntity>> signInWithEmail(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmail, [email, password]),
            returnValue: _i6.Future<_i7.Result<_i8.UserEntity>>.value(
              _i9.dummyValue<_i7.Result<_i8.UserEntity>>(
                this,
                Invocation.method(#signInWithEmail, [email, password]),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i7.Result<_i8.UserEntity>>.value(
                  _i9.dummyValue<_i7.Result<_i8.UserEntity>>(
                    this,
                    Invocation.method(#signInWithEmail, [email, password]),
                  ),
                ),
          )
          as _i6.Future<_i7.Result<_i8.UserEntity>>);

  @override
  _i6.Future<_i7.Result<_i8.UserEntity>> signUpWithEmail(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signUpWithEmail, [email, password]),
            returnValue: _i6.Future<_i7.Result<_i8.UserEntity>>.value(
              _i9.dummyValue<_i7.Result<_i8.UserEntity>>(
                this,
                Invocation.method(#signUpWithEmail, [email, password]),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i7.Result<_i8.UserEntity>>.value(
                  _i9.dummyValue<_i7.Result<_i8.UserEntity>>(
                    this,
                    Invocation.method(#signUpWithEmail, [email, password]),
                  ),
                ),
          )
          as _i6.Future<_i7.Result<_i8.UserEntity>>);

  @override
  _i6.Future<_i7.Result<_i8.UserEntity>> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i6.Future<_i7.Result<_i8.UserEntity>>.value(
              _i9.dummyValue<_i7.Result<_i8.UserEntity>>(
                this,
                Invocation.method(#signInWithGoogle, []),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i7.Result<_i8.UserEntity>>.value(
                  _i9.dummyValue<_i7.Result<_i8.UserEntity>>(
                    this,
                    Invocation.method(#signInWithGoogle, []),
                  ),
                ),
          )
          as _i6.Future<_i7.Result<_i8.UserEntity>>);

  @override
  _i6.Future<_i7.Result<_i8.UserEntity>> createProfile(
    Map<String, dynamic>? data, {
    _i10.File? photo,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createProfile, [data], {#photo: photo}),
            returnValue: _i6.Future<_i7.Result<_i8.UserEntity>>.value(
              _i9.dummyValue<_i7.Result<_i8.UserEntity>>(
                this,
                Invocation.method(#createProfile, [data], {#photo: photo}),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i7.Result<_i8.UserEntity>>.value(
                  _i9.dummyValue<_i7.Result<_i8.UserEntity>>(
                    this,
                    Invocation.method(#createProfile, [data], {#photo: photo}),
                  ),
                ),
          )
          as _i6.Future<_i7.Result<_i8.UserEntity>>);

  @override
  _i6.Future<_i7.Result<void>> sendResetPasswordEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendResetPasswordEmail, [email]),
            returnValue: _i6.Future<_i7.Result<void>>.value(
              _i9.dummyValue<_i7.Result<void>>(
                this,
                Invocation.method(#sendResetPasswordEmail, [email]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i7.Result<void>>.value(
              _i9.dummyValue<_i7.Result<void>>(
                this,
                Invocation.method(#sendResetPasswordEmail, [email]),
              ),
            ),
          )
          as _i6.Future<_i7.Result<void>>);

  @override
  _i6.Future<_i7.Result<void>> resetPassword(String? newPassword) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [newPassword]),
            returnValue: _i6.Future<_i7.Result<void>>.value(
              _i9.dummyValue<_i7.Result<void>>(
                this,
                Invocation.method(#resetPassword, [newPassword]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i7.Result<void>>.value(
              _i9.dummyValue<_i7.Result<void>>(
                this,
                Invocation.method(#resetPassword, [newPassword]),
              ),
            ),
          )
          as _i6.Future<_i7.Result<void>>);

  @override
  _i6.Future<_i7.Result<void>> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i6.Future<_i7.Result<void>>.value(
              _i9.dummyValue<_i7.Result<void>>(
                this,
                Invocation.method(#signOut, []),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i7.Result<void>>.value(
              _i9.dummyValue<_i7.Result<void>>(
                this,
                Invocation.method(#signOut, []),
              ),
            ),
          )
          as _i6.Future<_i7.Result<void>>);

  @override
  _i6.Future<_i7.Result<_i8.UserEntity>> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i6.Future<_i7.Result<_i8.UserEntity>>.value(
              _i9.dummyValue<_i7.Result<_i8.UserEntity>>(
                this,
                Invocation.method(#getCurrentUser, []),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i7.Result<_i8.UserEntity>>.value(
                  _i9.dummyValue<_i7.Result<_i8.UserEntity>>(
                    this,
                    Invocation.method(#getCurrentUser, []),
                  ),
                ),
          )
          as _i6.Future<_i7.Result<_i8.UserEntity>>);
}

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i11.AuthRemoteDataSource {
  @override
  _i6.Future<_i2.AuthResponse> signInWithEmail(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmail, [email, password]),
            returnValue: _i6.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_0(
                this,
                Invocation.method(#signInWithEmail, [email, password]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_0(
                this,
                Invocation.method(#signInWithEmail, [email, password]),
              ),
            ),
          )
          as _i6.Future<_i2.AuthResponse>);

  @override
  _i6.Future<_i2.AuthResponse> signUpWithEmail(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signUpWithEmail, [email, password]),
            returnValue: _i6.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_0(
                this,
                Invocation.method(#signUpWithEmail, [email, password]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_0(
                this,
                Invocation.method(#signUpWithEmail, [email, password]),
              ),
            ),
          )
          as _i6.Future<_i2.AuthResponse>);

  @override
  _i6.Future<_i2.AuthResponse> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i6.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_0(
                this,
                Invocation.method(#signInWithGoogle, []),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_0(
                this,
                Invocation.method(#signInWithGoogle, []),
              ),
            ),
          )
          as _i6.Future<_i2.AuthResponse>);

  @override
  _i6.Future<void> sendResetPasswordEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendResetPasswordEmail, [email]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updatePassword(String? newPassword) =>
      (super.noSuchMethod(
            Invocation.method(#updatePassword, [newPassword]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i3.UserModel> fetchUserProfile(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchUserProfile, [userId]),
            returnValue: _i6.Future<_i3.UserModel>.value(
              _FakeUserModel_1(
                this,
                Invocation.method(#fetchUserProfile, [userId]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i3.UserModel>.value(
              _FakeUserModel_1(
                this,
                Invocation.method(#fetchUserProfile, [userId]),
              ),
            ),
          )
          as _i6.Future<_i3.UserModel>);

  @override
  _i6.Future<_i3.UserModel> createUserProfile(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#createUserProfile, [data]),
            returnValue: _i6.Future<_i3.UserModel>.value(
              _FakeUserModel_1(
                this,
                Invocation.method(#createUserProfile, [data]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i3.UserModel>.value(
              _FakeUserModel_1(
                this,
                Invocation.method(#createUserProfile, [data]),
              ),
            ),
          )
          as _i6.Future<_i3.UserModel>);

  @override
  _i6.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String> uploadAvatar(String? userId, _i10.File? photo) =>
      (super.noSuchMethod(
            Invocation.method(#uploadAvatar, [userId, photo]),
            returnValue: _i6.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#uploadAvatar, [userId, photo]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#uploadAvatar, [userId, photo]),
              ),
            ),
          )
          as _i6.Future<String>);
}

/// A class which mocks [AuthLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLocalDataSource extends _i1.Mock
    implements _i12.AuthLocalDataSource {
  @override
  _i6.Future<void> cacheUser(_i3.UserModel? user) =>
      (super.noSuchMethod(
            Invocation.method(#cacheUser, [user]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> clearUser() =>
      (super.noSuchMethod(
            Invocation.method(#clearUser, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [HomeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRepository extends _i1.Mock implements _i13.HomeRepository {
  @override
  _i6.Future<_i7.Result<List<_i14.BannerEntity>>> getBanners() =>
      (super.noSuchMethod(
            Invocation.method(#getBanners, []),
            returnValue: _i6.Future<_i7.Result<List<_i14.BannerEntity>>>.value(
              _i9.dummyValue<_i7.Result<List<_i14.BannerEntity>>>(
                this,
                Invocation.method(#getBanners, []),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i7.Result<List<_i14.BannerEntity>>>.value(
                  _i9.dummyValue<_i7.Result<List<_i14.BannerEntity>>>(
                    this,
                    Invocation.method(#getBanners, []),
                  ),
                ),
          )
          as _i6.Future<_i7.Result<List<_i14.BannerEntity>>>);

  @override
  _i6.Future<_i7.Result<_i15.UpcomingAppointmentEntity?>> getUpcoming(
    String? profileId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUpcoming, [profileId]),
            returnValue:
                _i6.Future<_i7.Result<_i15.UpcomingAppointmentEntity?>>.value(
                  _i9.dummyValue<_i7.Result<_i15.UpcomingAppointmentEntity?>>(
                    this,
                    Invocation.method(#getUpcoming, [profileId]),
                  ),
                ),
            returnValueForMissingStub:
                _i6.Future<_i7.Result<_i15.UpcomingAppointmentEntity?>>.value(
                  _i9.dummyValue<_i7.Result<_i15.UpcomingAppointmentEntity?>>(
                    this,
                    Invocation.method(#getUpcoming, [profileId]),
                  ),
                ),
          )
          as _i6.Future<_i7.Result<_i15.UpcomingAppointmentEntity?>>);

  @override
  _i6.Future<_i7.Result<List<_i16.SpecializationEntity>>>
  getSpecializations() =>
      (super.noSuchMethod(
            Invocation.method(#getSpecializations, []),
            returnValue:
                _i6.Future<_i7.Result<List<_i16.SpecializationEntity>>>.value(
                  _i9.dummyValue<_i7.Result<List<_i16.SpecializationEntity>>>(
                    this,
                    Invocation.method(#getSpecializations, []),
                  ),
                ),
            returnValueForMissingStub:
                _i6.Future<_i7.Result<List<_i16.SpecializationEntity>>>.value(
                  _i9.dummyValue<_i7.Result<List<_i16.SpecializationEntity>>>(
                    this,
                    Invocation.method(#getSpecializations, []),
                  ),
                ),
          )
          as _i6.Future<_i7.Result<List<_i16.SpecializationEntity>>>);

  @override
  _i6.Future<_i7.Result<_i17.UserProfileEntity>> getUserProfile(
    String? authId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfile, [authId]),
            returnValue: _i6.Future<_i7.Result<_i17.UserProfileEntity>>.value(
              _i9.dummyValue<_i7.Result<_i17.UserProfileEntity>>(
                this,
                Invocation.method(#getUserProfile, [authId]),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i7.Result<_i17.UserProfileEntity>>.value(
                  _i9.dummyValue<_i7.Result<_i17.UserProfileEntity>>(
                    this,
                    Invocation.method(#getUserProfile, [authId]),
                  ),
                ),
          )
          as _i6.Future<_i7.Result<_i17.UserProfileEntity>>);
}

/// A class which mocks [HomeRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRemoteDataSource extends _i1.Mock
    implements _i18.HomeRemoteDataSource {
  @override
  _i6.Future<List<_i19.BannerModel>> fetchBanners() =>
      (super.noSuchMethod(
            Invocation.method(#fetchBanners, []),
            returnValue: _i6.Future<List<_i19.BannerModel>>.value(
              <_i19.BannerModel>[],
            ),
            returnValueForMissingStub: _i6.Future<List<_i19.BannerModel>>.value(
              <_i19.BannerModel>[],
            ),
          )
          as _i6.Future<List<_i19.BannerModel>>);

  @override
  _i6.Future<_i20.UpcomingAppointmentModel?> fetchUpcoming(String? profileId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchUpcoming, [profileId]),
            returnValue: _i6.Future<_i20.UpcomingAppointmentModel?>.value(),
            returnValueForMissingStub:
                _i6.Future<_i20.UpcomingAppointmentModel?>.value(),
          )
          as _i6.Future<_i20.UpcomingAppointmentModel?>);

  @override
  _i6.Future<List<_i21.SpecializationModel>> fetchSpecializations() =>
      (super.noSuchMethod(
            Invocation.method(#fetchSpecializations, []),
            returnValue: _i6.Future<List<_i21.SpecializationModel>>.value(
              <_i21.SpecializationModel>[],
            ),
            returnValueForMissingStub:
                _i6.Future<List<_i21.SpecializationModel>>.value(
                  <_i21.SpecializationModel>[],
                ),
          )
          as _i6.Future<List<_i21.SpecializationModel>>);

  @override
  _i6.Future<_i4.UserProfileModel> fetchUserProfile(String? authId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchUserProfile, [authId]),
            returnValue: _i6.Future<_i4.UserProfileModel>.value(
              _FakeUserProfileModel_2(
                this,
                Invocation.method(#fetchUserProfile, [authId]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i4.UserProfileModel>.value(
              _FakeUserProfileModel_2(
                this,
                Invocation.method(#fetchUserProfile, [authId]),
              ),
            ),
          )
          as _i6.Future<_i4.UserProfileModel>);
}

/// A class which mocks [HomeLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeLocalDataSource extends _i1.Mock
    implements _i22.HomeLocalDataSource {
  @override
  _i6.Future<void> cacheBanners(List<_i19.BannerModel>? banners) =>
      (super.noSuchMethod(
            Invocation.method(#cacheBanners, [banners]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> cacheSpecializations(
    List<_i21.SpecializationModel>? specializations,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cacheSpecializations, [specializations]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}
